### ISSUE TITLE
Version 0.4.2 on Maven Central

### ISSUE THREAD

**Issue by stepwise-alan** [ckaestne/TypeChef#47]
Hi @ckaestne and TypeChef devs,

I noticed that there is only version 0.4.1 of TypeChef on Maven Central, while the master branch on GitHub is version 0.4.2. I noticed that 0.4.2 fixes some bugs from 0.4.1. Do you plan to release the latest version of TypeChef on Maven Central?

Thanks!

**Comment by ckaestne** [comment]
sorry, I don't currently have any plans to further maintain the project. I hope compilation and sbt's publish local still provides a path toward using the latest changes.
